---
title: "Stat 223 Coding Standards"
output: html_document
---

We strive to adhere to the standards outlined in the [tidyverse style guide](http://style.tidyverse.org/). Specifically, we:

1. Avoid spaces (" ") in filenames. Use `-` or `_` instead (ie `homework-1` 
instead of `homework 1`)

2. Use consistent indentation for code bodies, etc.

3. Use gets operator `<-` instead of equals operator `=` for assignment.

4. One space on either side of ` <- ` operator.

5. Use `for (...` instead of `for(...`. Same for `if` and start of functions.

6. Use vectorization whenever possible.

7. Use `TRUE` and `FALSE` instead of `T` and `F`.

8. Favor `sapply` function over loops for simple problems.

9. R scripts should be run correctly from a clean R environment with the current working directory being the directory containing the script.

10. Use meaningful variable names.

11. Use `snake_case` for variable names.

12. Load packages at the start of the script using the `library()` function.

13. Avoid "hard coding" the same value in several places; instead set a variable once and use the variable in the place of hard coded values.

14. Avoid copying and pasting large sections of code; instead write a function that carries out the needed operation.
