---
title: "Resources"
output: html_document
---

## Course Resources
### [Coding Standards](coding-standards.html)
+ General guidelines for best coding practices.

### [Confidence Interval Formulas](ci_formulas.html)
+ Handy reference for confidence interval formulas for both mean and proportion 
estimates.

### [Simulation Study Outline](sim-study-outline.html)
+ General guideline for performing simulation studies.

## Additional Resources
While not required, these resources will help you grow in your understanding of
R.

### [Hands-On Programming with R](https://rstudio-education.github.io/hopr/){target="_blank"}
+ New resource that teaches basic R programming in a very aproachable manner.

### [Modern Dive](https://moderndive.com/index.html){target="_blank"}
+ An Introduction to Statistical and Data Sciences via R

### [R for Data Science](http://r4ds.had.co.nz){target="_blank"}
* Great resource for learning modern data science techniques using R.
* Focusses on the [tidyverse](https://www.tidyverse.org) and how various tools
enable different aspects of the Data Science process.

### [Introduction to R](https://colinfay.me/intro-to-r/){target="_blank"}
+ Generally approachable introduction to the R language.

### [R Graphics Cookbook](https://r-graphics.org/){target="_blank"}
+ Second edition containing 150+ recipes for creating excellent graphics in R.

### [Efficient R Programming](https://csgillespie.github.io/efficientR/){target="_blank"}
* Great resource for becoming more familiar with R and using it more effectively.

### [Advanced R](https://adv-r.hadley.nz){target="_blank"}
* Work in progress 2nd edition.
* Great for a deep dive into R.

### [Mastering Shiny](https://mastering-shiny.org/){target="_blank"}
* Work in progress book about [Shiny](http://shiny.rstudio.com/){target="_blank"}